### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Generated)
add_subdirectory(Interface)
add_subdirectory(InterfaceContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Generated_QtQuick3D_Cohete11plugin
    Interfaceplugin
    InterfaceContentplugin
    QtQuickDesignerComponents)