### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(APP_01)
add_subdirectory(APP_01Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    APP_01plugin
    APP_01Contentplugin
    QtQuickDesignerComponents)